channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.2
- pip:
  - mlflow==2.15.0
  - attrs==21.2.0
  - brotli==1.0.9
  - click==8.1.7
  - openai==1.37.1
  - pathlib==1.0.1
  - rich==13.7.1
  - tenacity==8.4.1
  - tiktoken==0.7.0
name: mlflow-env
